name: labPhp

networks:
  labPhp:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: labphp
    container_name: labPhp-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000" #symfony
      - "9003:9003" #xdebug
    volumes:
      - ./www:/var/www
    networks:
      - labPhp
    depends_on:
      postgres:
        condition:  service_started
      nginx:
        condition:  service_started

  nginx:
    image: nginx:1.27-alpine
    container_name: labPhp-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - labPhp
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:17.2
    container_name: labPhp-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
      - ./docker-compose/postgres/data:/var/lib/postgresql/data:rw
    networks:
      - labPhp